version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    labels:
      - dependencies
    groups:
      patch-minor:
        update-types:
          - patch
          - minor
