services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: backend_starter
      POSTGRES_PASSWORD: backend_starter
      POSTGRES_USER: backend_starter
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U backend_starter -d backend_starter']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
